jfs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('', include('portal.urls')),
    path('', include('admin_page.urls')),
    path('', include('staff.urls'))
]

handler404 = "portal.views.page_not_found_view"

portal/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("login/", views.login_page, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("profile/", views.home, name="home"),
    path("forgot_password/", views.forgot_password, name="forgot_password"),
    path("profile/<str:id>", views.profile, name="profile"),
    path("upload-photo/<int:id>", views.upload_photo, name="upload_photo"),
]

portal/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    GENDERS = (
        ('M','Male'),
        ('F', 'Female')
    )
    ROLES = (
        ('staff', 'staff'),
        ('student', 'student')
    )
    gender = models.CharField(max_length=10, choices=GENDERS, blank=True)
    role = models.CharField(max_length=10, choices=ROLES, default=ROLES[1][1])
    phone = models.CharField(max_length=12, blank=True)
    other_names = models.CharField(max_length=60, blank=True)
    photo = models.ImageField(blank=True, null=True, upload_to="uploads/users/", default="uploads/users/default.png")

class PendingPhoto(models.Model):
    photo = models.ImageField(upload_to="uploads/users/")
    user = models.OneToOneField(User, editable=True, on_delete=models.CASCADE)

class Staff(User):
    class Meta:
        verbose_name = 'Staff'
    STAFFROLES = (
        ('cleaner', 'Cleaner'),
        ('teacher', 'Teacher'),
        ('headteacher', 'Head Teacher'),
        ('norole', 'No Role'),
        ('security', 'Security'),
    )
    staff_role = models.CharField(max_length=20, choices=STAFFROLES)
    date_employed = models.DateField()
    salary = models.IntegerField(blank=True, null=True)

class ClassFees(models.Model):
    class Meta:
        verbose_name_plural = "Classes fees"
    classes = (
        ('Creche', 'Creche'),
        ('PreKg', 'PreKg'),
        ('Kindergarten', 'Kindergarten'),
        ('Nursery 1', 'Nursery 1'),
        ('Nursery 2', 'Nursery 2'),
        ('Grade 1', 'Grade 1'),
        ('Grade 2', 'Grade 2'),
        ('Grade 3', 'Grade 3'),
        ('Grade 4', 'Grade 4'),
        ('Grade 5', 'Grade 5'),
    )
    name = models.CharField(max_length=30, choices=classes)
    new_fee = models.IntegerField(default=0)
    return_fee = models.IntegerField(default=0)

class Class(models.Model):
    class Meta:
        verbose_name_plural = "Classes"
    classes = (
        ('Creche', 'Creche'),
        ('PreKg', 'PreKg'),
        ('Kindergarten', 'Kindergarten'),
        ('Nursery 1', 'Nursery 1'),
        ('Nursery 2', 'Nursery 2'),
        ('Grade 1', 'Grade 1'),
        ('Grade 2', 'Grade 2'),
        ('Grade 3', 'Grade 3'),
        ('Grade 4', 'Grade 4'),
        ('Grade 5', 'Grade 5'),
    )
    name = models.CharField(max_length=30, choices=classes)
    subclass = models.CharField(max_length=30, null=True, blank=True)
    teacher = models.ForeignKey(Staff, on_delete=models.SET_NULL, null=True, blank=True)

class Student(User):
    class Meta:
        verbose_name = 'Student'
    current_class = models.ForeignKey(Class, on_delete=models.SET_NULL, null=True)
    date_admitted = models.DateField()
    dob = models.DateField()

staff/models.py
from django.db import models
from portal.models import Staff
from datetime import time

# Create your models here.
class Test(models.Model):
    name = models.CharField(max_length=40)
    teacher = models.ForeignKey(Staff, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    time = models.TimeField(default=time.fromisoformat("00:10"))
    done = models.IntegerField(default=0)
    code = models.CharField(max_length=5, null=True, blank=True)

class Question(models.Model):
    number = models.IntegerField()
    text = models.TextField()
    test = models.ForeignKey(Test, on_delete=models.CASCADE)

class Option(models.Model):
    text = models.TextField()
    option_id = models.IntegerField()
    answer = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

portal/views.py
from datetime import time
from django.http import Http404
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import Staff, Student, User, PendingPhoto
from django.contrib import messages

# Create your views here.
def login_page(request):
    if request.method == 'POST':
        user = authenticate(username=request.POST.get('id'), password=request.POST.get('password'))
        if user:
            login(request, user)
            if user.is_superuser:
                return redirect('staff')
            return redirect('home')
        else:
            messages.error(request, "Incorrect ID or password")
            return redirect('login')
    return render(request, 'login.html')

@login_required
def profile(request, id):
    user = User.objects.get(username=id)
    if user:
        if user.role == "student":
            user = Student.objects.get(username=id)
        elif user.role == "staff":
            user = Staff.objects.get(username=id)
    else:
        raise Http404
    return render(request, 'profile.html', {"person": user})

@login_required
def home(request):
    return profile(request, request.user.username)

def upload_photo(request, id):
    user = User.objects.filter(username=id).first()
    if user:
        try:
            user.pendingphoto.delete()
        except:
            pass
        photo = PendingPhoto(photo=request.FILES.get('photo'), user=user)
        photo.save()
    return redirect('profile', id=id)

def page_not_found_view(request, exception):
    return render(request, '404.html', status=404)

def forgot_password(request):
    return render(request, 'forgot-password.html')

def logout_user(request):
    logout(request)
    return redirect('login')

portal/templates/create-test.html
{% extends 'bases/base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid pt-3">
  <div class="row removable">
    <div class="col-lg-8">
      <h3 class="text-center" spellcheck="false" data-ms-editor="true">
        Test Name
      </h3>
    </div>
    <div class="col-lg-4">
      <button class="btn btn-primary mb-4" type="button">Save</button>
      <button class="btn btn-secondary mb-4" type="button">Close</button>
    </div>
  </div>
  <template question-template>
    <li questionNumber>
      <div class="input-group input-group-outline mb-3">
        <input type="text" placeholder="Question" class="form-control" required />
        <button type="button" class="btn btn-link me-auto border-0 q-delete-btn btn-icons">
          <i class="material-icons text-lg">delete</i>
        </button>
      </div>
      <ol type="A">
        <!-- Options go here -->
      </ol>
      <button type="button" class="btn bg-gradient-primary buttons add_option"><i class="material-icons opacity-10">add</i>option</button>
    </li>
  </template>
  <template option-template>
    <li optionNumber>
      <div class="input-group input-group-outline mb-3">
        <input type="text" class="form-control" placeholder="Option" required />
        <button type="button" class="btn btn-link me-auto border-0 btn-icons choose-ans">
          <i class="material-icons text-lg">done_outline</i>
        </button>
        <button class="btn btn-link me-auto border-0 q-delete-btn btn-icons">
          <i class="material-icons text-lg">delete</i>
        </button>
      </div>
    </li>
  </template>
  <div class="card">
    <div class="card-body">
      <form role="form" class="text-start" method="post" action="">
        {% csrf_token %}
        <div>
          <ol type="1" id="questions">
            <!-- Question div -->
            
            <!-- Question div end -->
          </ol>

        </div>
        <div class="text-center">
          <button type="button" id="add_question" class="btn bg-gradient-primary w-100 my-4 mb-2">
            Add question
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

<head>
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
</head>
<script src="{% static 'js/create-test.js' %}"></script>
{% endblock %}

portal/templates/edit-test.html
{% extends 'bases/base.html' %}
{% load static %}
{% block title %}
  {{test.name}}
{% endblock %}
{% block content %}
<script src="{% static 'js/plugins/html-duration-picker.min.js' %}"></script>
<div class="container-fluid pt-3">
  <div class="row removable">
    <div class="col-lg-12">
      <h3 class="text-center" spellcheck="false" data-ms-editor="true">
        {{test.name}}
      </h3>
    </div>
  </div>
  <template question-template>
    <li questionNumber>
      <div class="input-group input-group-outline mb-3">
        <input type="text" placeholder="Question" class="form-control" required />
        <button type="button" class="btn btn-link me-auto border-0 q-delete-btn btn-icons">
          <i class="material-icons text-lg">delete</i>
        </button>
      </div>
      <ol type="A">
        <!-- Options go here -->
      </ol>
      <button type="button" class="btn bg-gradient-primary buttons add_option"><i class="material-icons opacity-10">add</i>option</button>
    </li>
  </template>
  <template option-template>
    <li optionNumber>
      <div class="input-group input-group-outline mb-3">
        <input type="text" class="form-control" placeholder="Option" required/>
        <button type="button" class="btn btn-link me-auto border-0 btn-icons choose-ans">
          <i class="material-icons text-lg">done_outline</i>
        </button>
        <button type="button" class="btn btn-link me-auto border-0 q-delete-btn btn-icons">
          <i class="material-icons text-lg">delete</i>
        </button>
      </div>
    </li>
  </template>
  <div class="card">
    <div class="card-body">
      <form role="form" class="text-start" id="form" method="post" action="">
        {% csrf_token %}
        <div class="col-lg-4">
          <button class="btn btn-primary mb-4" type="submit">Save</button>
          <button class="btn btn-success mb-4" type="button">Preview</button>
          <a href="{% url 'tests' %}" class="btn btn-secondary mb-4" id="close-test" type="button">Close</a>
        </div>
        <div>
          <ol type="1" id="questions">
            <!-- Question div -->
              {% for question in test.question_set.all %}
              <li questionNumber="{{question.number}}">
                <div class="input-group input-group-outline mb-3">
                  <input type="text" placeholder="Question" name="{{question.number}}" class="form-control" required value="{{question.text}}" />
                  <button type="button" class="btn btn-link me-auto border-0 q-delete-btn btn-icons">
                    <i class="material-icons text-lg">delete</i>
                  </button>
                </div>
                <ol type="A">
                {% for option in question.option_set.all %}
                <li optionNumber="{{quesion.number}}-{{option.option_id}}">
                  <div class="input-group input-group-outline mb-3">
                    <input type="text" class="form-control" name="{{question.number}}-{{option.option_id}}" placeholder="Option" required value="{{option.text}}"/>
                    <button type="button" class="btn btn-link me-auto border-0 btn-icons choose-ans">
                      <i class="material-icons text-lg">
                      {% if option.answer %}
                        check_circle
                      {% else %}
                        done_outline
                      {% endif %}
                      </i>
                    </button>
                    <button type="button" class="btn btn-link me-auto border-0 q-delete-btn btn-icons">
                      <i class="material-icons text-lg">delete</i>
                    </button>
                  </div>
                </li>
                {% endfor %}  
                </ol>
                <button type="button" class="btn bg-gradient-primary buttons add_option"><i class="material-icons opacity-10">add</i>option</button>
              </li>
            {% endfor %}
            <!-- Question div end -->
          </ol>
        </div>
        <div class="text-center">
          <button type="button" id="add_question" class="btn bg-gradient-primary w-100 my-4 mb-2">
            Add question
          </button>
        </div>
        <button class="btn btn-primary mb-4" type="submit">Save</button>
      </form>
    </div>
  </div>
</div>

<head>
  <link rel="stylesheet" type="text/css" href="{% static 'css/edit-test.css' %}" />
</head>
<script src="{% static 'js/edit-test.js' %}" defer></script>
{% endblock %}

portal/templates/empty.html
<div class="row min-vh-80">
    <div class="col-6 mx-auto">
      <div class="card mt-4">
        <div class="card-body">
          <h2 style="text-align:center;margin-top:0%">Nothing here</h2>
        </div>
      </div>
    </div>
  </div>

portal/templates/forgot-password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
  <title>
    JFS Portal
  </title>
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <!-- Nucleo Icons -->
  <link href="{% static 'css/nucleo-icons.css' %}" rel="stylesheet" />
  <link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- Material Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <!-- CSS Files -->
  <link id="pagestyle" href="{% static 'css/material-dashboard.css' %}" rel="stylesheet" />
</head>

<body class="bg-gray-200">
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg blur border-radius-xl top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid ps-2 pe-0">
            <a class="navbar-brand font-weight-bolder ms-lg-0 ms-3">
              Jules foundation school
            </a>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>
  <main class="main-content  mt-0">
    <div class="page-header align-items-start min-vh-100" style="background-image: url('https://images.unsplash.com/photo-1497294815431-9365093b7331?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1950&q=80');">
      <span class="mask bg-gradient-dark opacity-6"></span>
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-4 col-md-8 col-12 mx-auto">
            <div class="card z-index-0 fadeIn3 fadeInBottom">
              <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                <div class="bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1">
                  <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">Sign in</h4>
                </div>
              </div>
              {% include 'messages.html' %}
              <div class="card-body">
                <form role="form" class="text-start" method="post">
                  {% csrf_token %}
                  <div class="input-group input-group-outline my-3">
                    <label class="form-label">ID number</label>
                    <input type="text" name="id" class="form-control" required>
                  </div>
                  <p class="text-center">A message will be sent to the email and WhatsApp number associated with this user</p>
                  <div class="text-center">
                    <button type="submit" class="btn bg-gradient-primary w-100 my-4 mb-2">Sign in</button>
                  </div>
                  <p class="mt-4 text-sm text-center">
                    <a href="{% url 'login' %}" class="text-primary text-gradient font-weight-bold">Login</a>
                  </p>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      <footer class="footer position-absolute bottom-2 py-2 w-100">
        <div class="container">
          <div class="row align-items-center justify-content-lg-between">
            <div class="col-12 col-md-6 my-auto">
              <div class="copyright text-center text-sm text-white text-lg-start">
                © <script>
                  document.write(new Date().getFullYear())
                </script>,
                made with <i class="fa fa-heart" aria-hidden="true"></i> by
                <a href="https://www.creative-tim.com" class="font-weight-bold text-white" target="_blank">Creative Tim</a>
                for a better web.
              </div>
            </div>
            <div class="col-12 col-md-6">
              <ul class="nav nav-footer justify-content-center justify-content-lg-end">
                <li class="nav-item">
                  <a href="https://www.creative-tim.com" class="nav-link text-white" target="_blank">Creative Tim</a>
                </li>
                <li class="nav-item">
                  <a href="https://www.creative-tim.com/presentation" class="nav-link text-white" target="_blank">About Us</a>
                </li>
                <li class="nav-item">
                  <a href="https://www.creative-tim.com/blog" class="nav-link text-white" target="_blank">Blog</a>
                </li>
                <li class="nav-item">
                  <a href="https://www.creative-tim.com/license" class="nav-link pe-0 text-white" target="_blank">License</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </main>
  <!--   Core JS Files   -->
  <script src="{% static 'js/core/popper.min.js' %}"></script>
  <script src="{% static 'js/core/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
  <script src="{% static 'js/plugins/smooth-scrollbar.min.js' %}"></script>
  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>
  <!-- Github buttons -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'js/material-dashboard.min.js' %}"></script>
</body>

</html>

portal/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
  <title>
    JFS Portal
  </title>
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <!-- Nucleo Icons -->
  <link href="{% static 'css/nucleo-icons.css' %}" rel="stylesheet" />
  <link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- Material Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <!-- CSS Files -->
  <link id="pagestyle" href="{% static 'css/material-dashboard.css' %}" rel="stylesheet" />
</head>

<body class="bg-gray-200">
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg blur border-radius-xl top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid ps-2 pe-0">
            <a class="navbar-brand font-weight-bolder ms-lg-0 ms-3">
              Jules foundation school
            </a>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>
  <main class="main-content  mt-0">
    <div class="page-header align-items-start min-vh-100" style="background-image: url('https://images.unsplash.com/photo-1497294815431-9365093b7331?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1950&q=80');">
      <span class="mask bg-gradient-dark opacity-6"></span>
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-4 col-md-8 col-12 mx-auto">
            <div class="card z-index-0 fadeIn3 fadeInBottom">
              <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                <div class="bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1">
                  <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">Sign in</h4>
                </div>
              </div>
              {% include 'messages.html' %}
              <div class="card-body">
                <form role="form" class="text-start" method="post">
                  {% csrf_token %}
                  <div class="input-group input-group-outline my-3">
                    <label class="form-label">ID number</label>
                    <input type="text" name="id" class="form-control" required>
                  </div>
                  <div class="input-group input-group-outline mb-3">
                    <label class="form-label">Password</label>
                    <input type="password" class="form-control" name="password" required>
                  </div>
                  <div class="text-center">
                    <button type="submit" class="btn bg-gradient-primary w-100 my-4 mb-2">Sign in</button>
                  </div>
                  <p class="mt-4 text-sm text-center">
                    Forgot 
                    <a href="{% static 'pages/sign-up.html' %}" class="text-primary text-gradient font-weight-bold">password?</a>
                  </p>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      <footer class="footer position-absolute bottom-2 py-2 w-100">
        <div class="container">
          <div class="row align-items-center justify-content-lg-between">
            <div class="col-12 col-md-6 my-auto">
              <div class="copyright text-center text-sm text-white text-lg-start">
                © <script>
                  document.write(new Date().getFullYear())
                </script>,
                made with <i class="fa fa-heart" aria-hidden="true"></i> by
                <a href="https://www.creative-tim.com" class="font-weight-bold text-white" target="_blank">Creative Tim</a>
                for a better web.
              </div>
            </div>
            <div class="col-12 col-md-6">
              <ul class="nav nav-footer justify-content-center justify-content-lg-end">
                <li class="nav-item">
                  <a href="https://www.creative-tim.com" class="nav-link text-white" target="_blank">Creative Tim</a>
                </li>
                <li class="nav-item">
                  <a href="https://www.creative-tim.com/presentation" class="nav-link text-white" target="_blank">About Us</a>
                </li>
                <li class="nav-item">
                  <a href="https://www.creative-tim.com/blog" class="nav-link text-white" target="_blank">Blog</a>
                </li>
                <li class="nav-item">
                  <a href="https://www.creative-tim.com/license" class="nav-link pe-0 text-white" target="_blank">License</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </main>
  <!--   Core JS Files   -->
  <script src="{% static 'js/core/popper.min.js' %}"></script>
  <script src="{% static 'js/core/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
  <script src="{% static 'js/plugins/smooth-scrollbar.min.js' %}"></script>
  <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>
  <!-- Github buttons -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'js/material-dashboard.min.js' %}"></script>
</body>

</html>

portal/templates/messages.html
{% if messages %}
<div class="card-body p-3 pb-0">
  {% for message in messages %}
  <div class="container">
    {% if message.tags == "error" %}
    <div class="alert alert-danger alert-dismissible text-white" role="alert">
    {% else %}
    <div class="alert alert-{{message.tags}} alert-dismissible text-white" role="alert">
    {% endif %}
      <span class="text-sm">{{ message }}</span>
      <button type="button" class="btn-close text-lg py-3 opacity-10" data-bs-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endfor %}
</div>
{% endif %}

portal/templates/tests.html
{% extends 'bases/base.html' %}
{% load static %}
{% block title %}Tests{% endblock %}
{% block content %}
<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
<div class="container-fluid py-4">
  <div class="row">
    <div class="col-12">
      <div class="card my-4">
        <div class="card-header pb-0 p-3"></div>
        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
          <div
            class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3"
          >
            <div class="row">
              <div class="col-6 d-flex align-items-center">
                <h6 class="text-white text-capitalize ps-3">Tests</h6>
              </div>
              <div
                class="col-6 text-end"
                style="right: 10px; position: relative"
              >
                <button
                  type="button"
                  class="btn bg-gradient-dark mb-0"
                  data-toggle="modal"
                  data-target="#newSubClassModal"
                >
                  <i class="material-icons opacity-10">add</i> New test
                </button>
              </div>
            </div>
          </div>
        </div>
        <div class="card-body px-0 pb-2">
          <div class="table-responsive p-0">
            <table class="table align-items-center mb-0">
              <thead>
                <tr>
                  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                    Name
                  </th>
                  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                    status
                  </th>
                  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                    taken
                  </th>
                  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
                    code
                  </th>
                  <th class="text-secondary opacity-7"></th>
                </tr>
              </thead>
              <tbody>
                {% for test in tests %}
                <tr>
                  <td class="text-center align-middle text-sm">
                    <a href="{% url 'students' %}?class={{class.id}}">
                      <span> {{test.name|title}} </span>
                    </a>
                  </td>
                  <td class="align-middle text-center text-sm">
                    {% if test.status %}
                    <span class="badge badge-sm bg-gradient-success">Public</span>
                    {% else %}
                    <span class="badge badge-sm bg-gradient-secondary">Private</span>
                    {% endif %}
                  </td>
                  <td class="align-middle text-center text-sm">
                    <span></span>
                  </td>
                  <td class="align-middle text-center text-sm">
                    <span>{{test.code}}</span>
                  </td>
                  <td class="align-middle">
                    <a href="/edit-test/{{test.id}}">
                        <i class="material-icons opacity-10">open_in_new</i>
                    </a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="newSubClassModal">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">New Test</h4>
      </div>
      <!-- Modal body -->
      <div class="modal-body">
        <div class="card-body">
          <form
            role="form"
            class="text-start"
            method="post"
            action="{% url 'new_test' %}"
          >
            {% csrf_token %}
            <div class="input-group input-group-outline mb-3">
              <label class="form-label">Name</label>
              <input
                type="text"
                class="form-control"
                name="name"
                required
              />
            </div>
            <div class="text-center">
              <button
                type="submit"
                class="btn bg-gradient-primary w-100 my-4 mb-2"
              >
                Create
              </button>
            </div>
          </form>
        </div>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          Close
        </button>
      </div>
    </div>
  </div>
</div>
{% endblock %}