admin_page/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("website/", views.website, name="website"),

    path("edit-blogs/", views.editblogs, name="edit_blogs"),
    path("new-blog/", views.new_blog, name="new_blog"),
    path("update-blog/", views.update_blog, name="update_blog"),
    path("delete-blog/<int:id>", views.delete_blog, name="delete_blog"),

    path("staff/", views.staff, name="staff"),
    path("new-staff/", views.new_staff, name="new_staff"),
    path("update-staff/", views.update_staff, name="update_staff"),
    path("delete-staff/<str:id>", views.delete_staff, name="delete_staff"),

    path("edit-fees/", views.edit_fees, name="edit_fees"),
    
    path("students/", views.students, name="students"),
    path("new-student/", views.new_student, name="new_student"),
    path("update-student/", views.update_student, name="update_student"),
    path("delete-student/<str:id>", views.delete_student, name="delete_student"),

    path("classes/", views.classes, name="classes"),
    path("new-subclass/", views.new_subclass, name="new_subclass"),
    path("delete-class/<int:id>", views.delete_class, name="delete_class"),
    # path("delete-migrate/", views.delete_and_migrate_class, name="delete_and_migrate_class"),

    path("messages/", views.get_messages, name="messages"),
    path("delete-message/<int:id>", views.delete_message, name="delete_message"),

    path("contact-list/", views.contact_list, name="contact_list"),
    path("update-contact/", views.update_contact, name="update_contact"),
    path("delete-contact/<int:id>", views.delete_contact, name="delete_contact"),

    path("randoms/", views.randoms, name="randoms"),
    path("delete-random/<int:id>", views.delete_random, name="delete_random"),
    
    path("broadcast/", views.broadcast, name="broadcast"),

    path("discard-photo/<int:id>", views.discard_photo, name="discard_photo"),
    path("pending-photos/", views.pending_photos, name="pending_photos"),
    path("accept-photo/<int:id>", views.accept_photo, name="accept_photo"),
]

jfs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('', include('portal.urls')),
    path('', include('admin_page.urls')),
    path('', include('staff.urls'))
]

handler404 = "portal.views.page_not_found_view"

staff/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("edit-test/<int:id>", views.edit_test, name="edit_test"),
    path("new-test/", views.new_test, name="new_test"),
    path("delete-test/<int:id>", views.delete_test, name="delete_test"),    
    path("tests/", views.tests, name="tests"),
    path("preview-test/<int:id>", views.preview_test, name="preview_test"),
] 

admin_page/models.py
from django.db import models
from datetime import date

# Create your models here.


class Blog(models.Model):
    heading = models.CharField(max_length=120)
    desc = models.TextField()
    photo = models.ImageField(blank=True, null=True, upload_to="uploads/blogs/")
    date = models.DateField(default=date.today)

class Message(models.Model):
    name = models.CharField(max_length=50)
    subject = models.CharField(max_length=70)
    message = models.TextField()
    contact = models.CharField(max_length=150)
    time = models.DateTimeField(auto_now_add=True)

class Random(models.Model):
    photo = models.ImageField(upload_to="uploads/random/")

class Contact(models.Model):
    GENDERS = (
        ('M','Male'),
        ('F', 'Female')
    )
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    phone = models.CharField(max_length=12)
    gender = models.CharField(choices=GENDERS, max_length=7)
    email = models.CharField(max_length=50)
    whatsapp = models.CharField(max_length=12)

portal/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    GENDERS = (
        ('M','Male'),
        ('F', 'Female')
    )
    ROLES = (
        ('staff', 'staff'),
        ('student', 'student')
    )
    gender = models.CharField(max_length=10, choices=GENDERS, blank=True)
    role = models.CharField(max_length=10, choices=ROLES, default=ROLES[1][1])
    phone = models.CharField(max_length=12, blank=True)
    other_names = models.CharField(max_length=60, blank=True)
    photo = models.ImageField(blank=True, null=True, upload_to="uploads/users/", default="uploads/users/default.png")

class PendingPhoto(models.Model):
    photo = models.ImageField(upload_to="uploads/users/")
    user = models.OneToOneField(User, editable=True, on_delete=models.CASCADE)

class Staff(User):
    class Meta:
        verbose_name = 'Staff'
    STAFFROLES = (
        ('cleaner', 'Cleaner'),
        ('teacher', 'Teacher'),
        ('headteacher', 'Head Teacher'),
        ('norole', 'No Role'),
        ('security', 'Security'),
    )
    staff_role = models.CharField(max_length=20, choices=STAFFROLES)
    date_employed = models.DateField()
    salary = models.IntegerField(blank=True, null=True)

class ClassFees(models.Model):
    class Meta:
        verbose_name_plural = "Classes fees"
    classes = (
        ('Creche', 'Creche'),
        ('PreKg', 'PreKg'),
        ('Kindergarten', 'Kindergarten'),
        ('Nursery 1', 'Nursery 1'),
        ('Nursery 2', 'Nursery 2'),
        ('Grade 1', 'Grade 1'),
        ('Grade 2', 'Grade 2'),
        ('Grade 3', 'Grade 3'),
        ('Grade 4', 'Grade 4'),
        ('Grade 5', 'Grade 5'),
    )
    name = models.CharField(max_length=30, choices=classes)
    new_fee = models.IntegerField(default=0)
    return_fee = models.IntegerField(default=0)

class Class(models.Model):
    class Meta:
        verbose_name_plural = "Classes"
    classes = (
        ('Creche', 'Creche'),
        ('PreKg', 'PreKg'),
        ('Kindergarten', 'Kindergarten'),
        ('Nursery 1', 'Nursery 1'),
        ('Nursery 2', 'Nursery 2'),
        ('Grade 1', 'Grade 1'),
        ('Grade 2', 'Grade 2'),
        ('Grade 3', 'Grade 3'),
        ('Grade 4', 'Grade 4'),
        ('Grade 5', 'Grade 5'),
    )
    name = models.CharField(max_length=30, choices=classes)
    subclass = models.CharField(max_length=30, null=True, blank=True)
    teacher = models.ForeignKey(Staff, on_delete=models.SET_NULL, null=True, blank=True)

class Student(User):
    class Meta:
        verbose_name = 'Student'
    current_class = models.ForeignKey(Class, on_delete=models.SET_NULL, null=True)
    date_admitted = models.DateField()
    dob = models.DateField()

staff/models.py
from django.db import models
from portal.models import Staff
from datetime import time

# Create your models here.
class Test(models.Model):
    name = models.CharField(max_length=40)
    teacher = models.ForeignKey(Staff, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    time = models.TimeField(default=time.fromisoformat("00:10"))
    done = models.IntegerField(default=0)
    code = models.CharField(max_length=5, null=True, blank=True)

class Question(models.Model):
    number = models.IntegerField()
    text = models.TextField()
    test = models.ForeignKey(Test, on_delete=models.CASCADE)

class Option(models.Model):
    text = models.TextField()
    option_id = models.IntegerField()
    answer = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

student/models.py
from django.db import models

# Create your models here.

admin_page/views.py
import os
from this import s
from django.http import Http404, HttpResponse, JsonResponse
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.utils.dateparse import parse_date
from portal.models import Class, ClassFees, PendingPhoto, Staff, Student, User
from .models import Blog, Contact, Message, Random
from datetime import date
import string, random
from django.contrib import messages
from django.core.mail import send_mail, send_mass_mail
from django.conf import settings
from django.template import loader

# Create your views here.

def admin_login_required(f):
    def wrapper(request, *args, **kwargs):
        if request.user.is_superuser:
            return f(request, *args, **kwargs)
        else:
            raise Http404
    return wrapper

def del_photo(photo):
    try:
        if not photo.path.endswith("\default.png"):
            os.remove(photo.path)
    except:
        pass

@login_required
@admin_login_required
def website(request):
    return render(request, 'admin-page/website.html')

@login_required
@admin_login_required
def editblogs(request):
    return render(request, 'admin-page/edit-blogs.html', {"blogs": Blog.objects.all().order_by("-date")})

@login_required
@admin_login_required
def new_blog(request):
    if request.method == "POST":
        heading = request.POST.get('heading')
        desc = request.POST.get('desc')
        photo = request.FILES.get('photo')
        date = request.POST.get('date')
        blog = Blog(heading=heading, desc=desc, photo=photo)
        if date:
            blog.date = date
        blog.save()
        messages.success(request, "Blog created")
    return redirect('edit_blogs')

@login_required
@admin_login_required
def update_blog(request):
    if request.method == "POST":
        id = request.POST.get('id')
        blog = Blog.objects.get(id=id)
        if blog:
            messages.success(request, f"Blog {blog.heading} updated")
            heading = request.POST.get('heading')
            desc = request.POST.get('desc')
            date = request.POST.get('date')
            photo = request.FILES.get('photo')
            blog.heading = heading
            blog.desc = desc
            blog.date = parse_date(date)
            if photo:
                del_photo(blog.photo)
                blog.photo = photo
            blog.save()
        else:
            messages.error(request, "Blog was not found. Try refreshing the page")
    return redirect('edit_blogs')

@login_required
@admin_login_required
def delete_blog(request, id):
    blog = Blog.objects.get(id=id)
    if blog:
        messages.success(request, f"Blog {blog.heading} deleted")
        del_photo(blog.photo)
        blog.delete()
    else:
        messages.error(request, "Blog was not found. Try refreshing the page")
    return redirect('edit_blogs')

@login_required
@admin_login_required
def staff(request):
    return render(request, 'admin-page/staff.html', {"staff": Staff.objects.all().order_by('first_name')})

@login_required
@admin_login_required
def new_staff(request):
    if request.method == "POST":
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        onames = request.POST.get('onames')
        role = request.POST.get('role')
        email = request.POST.get('email')
        gender = request.POST.get('gender')
        phone = request.POST.get('phone')
        salary = request.POST.get('salary')
        pwd = request.POST.get('password')
        date_employed = request.POST.get('date_employed')
        last = Staff.objects.last()
        yr = str(date.today().year)[2:]
        if last:
            num = int(last.username[-3:])
        else:
            num = 1
        rand_pwd = ''.join(random.choices(string.ascii_lowercase+string.digits, k=8))
        password = rand_pwd if pwd == "" else pwd
        staff = Staff.objects.create_user(username=f'1{yr}{str(num+1).zfill(3)}', password=password, email=email, gender=gender,
            first_name=fname, last_name=lname, other_names=onames, role='staff', staff_role=role.lower(), phone=phone, salary=salary, date_employed=parse_date(date_employed))
        staff.save()

        if email != "":
            err = account_created_message(staff.email, staff.get_full_name(), staff.username, password if pwd != password else "*"*len(password), staff.staff_role)
            if err != 1:
                messages.error(request, "An email containing this user's credentials wasn't sent.")
            else:
                messages.success(request, "An email containing this user's credentials was sent successfully.")
        messages.success(request, f"Staff created")
    return redirect('staff')

@login_required
@admin_login_required
def update_staff(request):
    if request.method == "POST":
        uid = request.POST.get('id')
        staff = Staff.objects.filter(username=str(uid)).first()
        if staff:
            staff.first_name = request.POST.get('fname')
            staff.last_name = request.POST.get('lname')
            staff.other_names = request.POST.get('onames')
            staff.email = request.POST.get('email')
            staff.phone = request.POST.get('phone')
            staff.salary = request.POST.get('salary')
            
            role = request.POST.get('role')
            password = request.POST.get('password')
            if role != "norole":
                staff.role = role
            if password != "":
                staff.set_password(password)
            staff.save()
            messages.success(request, f"Staff {staff.username} Updated")
        else:
            messages.error(request, "Staff was not found. Try refreshing the page")
    return redirect('staff')

@login_required
@admin_login_required
def delete_staff(request, id):
    staff = Staff.objects.filter(username=id).first()
    if staff:
        del_photo(staff.photo)
        staff.delete()
    return HttpResponse()

@login_required
@admin_login_required
def classes(request):
    if request.method == "POST":
        cid = request.POST.get('class')
        tid = request.POST.get('teacher')
        c = Class.objects.get(id=cid)
        teacher = Staff.objects.filter(username=tid).first()
        if tid == "None" and c:
            c.teacher = None
            c.save()
            messages.success(request, f"{c.name} has been set to no teacher")
        elif teacher and c:
            c.teacher = teacher
            c.save()
            messages.success(request, f"{teacher.first_name} is now the teacher of {c.name}")
        else:
            messages.error(request, f"The staff or the class were nor found")
    return render(request, 'admin-page/classes.html', {"classes":Class.objects.all(), "teachers":Staff.objects.filter(staff_role__endswith="teacher").order_by("first_name")})

@login_required
@admin_login_required
def students(request):
    c = None
    class_id = request.GET.get('class')
    if class_id:
        get_class = Class.objects.get(id=class_id)
        if get_class:
            s = Student.objects.filter(current_class=get_class).order_by('first_name')
            c = get_class.name
    else:
        s = Student.objects.all().order_by('first_name')
    return render(request, 'admin-page/students.html', {'students': s, 'classes':Class.objects.all(), "c":c})

@login_required
@admin_login_required
def new_student(request):
    if request.method == "POST":
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        onames = request.POST.get('onames')
        email = request.POST.get('email')
        gender = request.POST.get('gender')
        phone = request.POST.get('phone')
        pwd = request.POST.get('password')
        date_admitted = request.POST.get('date_admitted')
        dob = request.POST.get('dob')
        last = Student.objects.last()
        yr = str(date.today().year)[2:]
        _class = Class.objects.filter(id=request.POST.get('class')).first()
        if last:
            num = int(last.username[-3:])
        else:
            num = 0
        rand_pwd = ''.join(random.choices(string.ascii_lowercase+string.digits, k=8))
        password = rand_pwd if pwd == "" else pwd
        student = Student.objects.create_user(username=f'{yr}{str(num+1).zfill(3)}', password=password, email=email, gender=gender,
            first_name=fname, last_name=lname, other_names=onames, role='student', current_class=_class, phone=phone, dob=parse_date(dob), date_admitted=parse_date(date_admitted))
        student.save()
        if email != "":
            err = account_created_message(student.email, student.get_full_name(), student.username, password if pwd != password else "*"*len(password), student.current_class)
            if err != 1:
                messages.error(request, "An email containing this user's credentials wasn't sent.")
            else:
                messages.success(request, "An email containing this user's credentials was sent successfully.")
        # Send message with twilio api

        messages.success(request, f"Student created")
    return redirect('students')

@login_required
@admin_login_required
def update_student(request):
    if request.method == "POST":
        uid = request.POST.get('id')
        student = Student.objects.get(username=str(uid))
        if student:
            student.first_name = request.POST.get('fname')
            student.last_name = request.POST.get('lname')
            student.other_names = request.POST.get('onames')
            student.email = request.POST.get('email')
            student.phone = request.POST.get('phone')
            
            _class = Class.objects.filter(id=request.POST.get('class')).first()
            password = request.POST.get('password')
            if _class != None:
                student.current_class = _class
            if password != "":
                student.set_password(password)
            student.save()

student/views.py
from django.shortcuts import render

# Create your views here.
def write_test(request):
    return render("test.html")

admin_page/templates/admin-page/broadcast-modal.html
<div class="modal fade" id="broadcastModal">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">
			<!-- Modal Header -->
			<div class="modal-header">
				<h4 class="modal-title">Broadcast message to {{set}}</h4>
			</div>
			<!-- Modal body -->
			<div class="modal-body">
				<div class="card-body">
					<form role="form"
						class="text-start"
						method="post"
						action="{% url 'broadcast' %}">
						{% csrf_token %}
                        <input type="hidden" name="set" value="{{set}}">
                        <div class="input-group input-group-outline mb-3">
							<label class="form-label">Subject</label>
							<input type="text" class="form-control" name="subject" required />
						</div>
						<div class="input-group input-group-outline mb-3">
							<textarea name="msg" class="form-control" cols="30" rows="10" placeholder="Message" required></textarea>
						</div>
						<div class="form-check form-switch ps-0">
							<input class="form-check-input ms-auto" type="checkbox" name="toEmail" id="emailSwitchCheckDefault" checked>
							<label class="form-check-label text-body ms-3 text-truncate w-80 mb-0" for="emailSwitchCheckDefault">To email</label>
						</div>
						<div class="form-check form-switch ps-0">
							<input class="form-check-input ms-auto" type="checkbox" name="toWA" id="whatsappSwitchCheckDefault" checked>
							<label class="form-check-label text-body ms-3 text-truncate w-80 mb-0" for="whatsappSwitchCheckDefault">To WhatsApp</label>
						</div>
						<div class="text-center">
							<button type="submit" class="btn bg-gradient-primary w-100 my-4 mb-2">
								Send
							</button>
						</div>
					</form>
				</div>
			</div>

			<!-- Modal footer -->
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">
					Close
				</button>
			</div>
		</div>
	</div>
</div>

admin_page/templates/admin-page/classes.html
{% extends 'portal/base.html' %}
{% load static %}
{% block title %}Classes{% endblock %}
{% block content %}
<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
<div class="container-fluid py-4">
	<div class="row">
		<div class="col-12">
			<div class="card my-4">
				<div class="card-header pb-0 p-3"></div>
				<div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
					<div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
						<div class="row">
							<div class="col-6 d-flex align-items-center">
								<h6 class="text-white text-capitalize ps-3">Class Table</h6>
							</div>
							<div class="col-6 text-end" style="right: 10px; position: relative">
								<button
									type="button"
									class="btn bg-gradient-dark mb-0"
									data-toggle="modal"
									data-target="#newSubClassModal">
									<i class="material-icons opacity-10">add</i> New subclass
								</button>
							</div>
						</div>
					</div>
				</div>
				<div class="card-body px-0 pb-2">
					<div class="table-responsive p-0">
						<table class="table align-items-center mb-0">
							<thead>
								<tr>
									<th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
										Class
									</th>
									<th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
										Class teacher
									</th>
									<th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
										No. of students
									</th>
									<th class="text-secondary opacity-7"></th>
								</tr>
							</thead>
							<tbody>
								{% for class in classes %}
								<tr>
									<td class="text-center align-middle text-sm">
										<a href="{% url 'students' %}?class={{class.id}}">
											<span>
												{{class.name|title}}
												{% if class.subclass %}
												{{class.subclass|title}}
												{% endif %}
											</span>
										</a>
									</td>
									<td class="align-middle text-center text-sm">
										{% if class.teacher %}
										<a href="{% url 'profile' id=class.teacher.username %}">
											<div class="px-2 py-1">
												<div class="flex-column justify-content-center">
													<h6 class="mb-0 text-sm">
														{{class.teacher.first_name}} {{class.teacher.first_name}}
														<p class="text-xs text-secondary mb-0">{{ class.teacher.username }}</p>
													</h6>
												</div>
											</div>
										</a>
										{% else %}
										<span>None</span>
										{% endif %}
									</td>
									<td class="align-middle text-center text-sm">
										<span>{{class.student_set.count}}</span>
									</td>
									<td class="align-middle">
										<a onclick="edit_class({{ class.id }})"
										type="button"
										class="text-secondary font-weight-bold text-xs"
										data-toggle="modal"
										data-target="#editClassModal">Edit
										</a>
									</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="newSubClassModal">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">
			<!-- Modal Header -->
			<div class="modal-header">
				<h4 class="modal-title">New subclass</h4>
			</div>

			<!-- Modal body -->
			<div class="modal-body">
				<div class="card-body">
					<form role="form"
						class="text-start"
						method="post"
						action="{% url 'new_subclass' %}">
						{% csrf_token %}
						<div class="input-group input-group-outline mb-3">
							<label class="form-label">Name of subclass 1</label>
							<input type="text" class="form-control" name="subclass1" required/>
						</div>
						<div class="input-group input-group-outline mb-3">
							<label class="form-label">Name of subclass 2</label>
							<input type="text" class="form-control" name="subclass2" required/>
						</div>
						<div class="input-group input-group-outline mb-3">
							<select name="parent_class" class="form-control" aria-placeholder="Class" required>
								<option selected disabled>-- Select parent class --</option>
								{% for class in classes %}
								{% if not class.subclass %}
								<option value="{{class.id}}">
									{{class.name}}
								</option>
								{% endif %}
								{% endfor %}
							</select>
						</div>
						<div class="text-center">
							<button type="submit" class="btn bg-gradient-primary w-100 my-4 mb-2">
								Create
							</button>
						</div>
					</form>
				</div>
			</div>

			<!-- Modal footer -->
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">
					Close
				</button>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="editClassModal">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">
			<!-- Modal Header -->
			<div class="modal-header">
				<h4 class="modal-title">Edit class teacher</h4>
			</div>

			<!-- Modal body -->
			<div class="modal-body">
				<div class="card-body">
					<form role="form" class="text-start" method="post">
						{% csrf_token %}
						<div class="input-group input-group-outline mb-3">
							<input type="hidden" name="class" id="class">
							<select name="teacher" id="teacher" class="form-control" aria-placeholder="Class teacher" required>
								<option selected value="None">-- Leave blank to remove the current teacher --</option>
								{% for teacher in teachers %}
									{% if teacher.class_set.count < 1 %}
										<option value="{{teacher.username}}">{{teacher.first_name}} {{teacher.last_name}}</option>
									{% endif %}
								{% endfor %}
							</select>
						</div>
						<p class="text-center" style="margin-bottom: 0px!important;">Assign a teacher to this class</p>
						<div class="text-center">
							<button type="submit" class="btn bg-gradient-primary w-100 my-4 mb-2">
								Update
							</button>
						</div>
					</form>
				</div>
			</div>
			<!-- Modal footer -->
			<div class="modal-footer">
				<button type="button" class="btn btn-danger" onclick="delete_class()">
					Delete
				</button>
				<button type="button" class="btn btn-secondary" data-dismiss="modal">
					Close
				</button>
			</div>
		</div>
	</div>
</div>
<script>
	function edit_class(id){
		$("#class").val(id)
	}
	function delete_class(){
		let id = $('#class').val()
		var a = confirm(
			"Are you sure you want to delete this class?\nNote: You have to assign all the students in this class to another class."
		);
		if (!a) return;
		fetch('/delete-class/'+id)
		.then((res) => {
			location.reload()
		});
	}
</script>
{% endblock %}

admin_page/templates/admin-page/edit-fees.html
{% extends 'portal/base.html' %}
{% load static %}
{% load humanize %}
{% block title %}Fees{% endblock %}
{% block content %}
<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
<div class="container-fluid py-4">
	<div class="row">
		<div class="col-12">
			<div class="card my-4">
				<div class="card-header pb-0 p-3"></div>
				<div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
					<div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
						<div class="row">
							<div class="col-6 d-flex align-items-center">
								<h6 class="text-white text-capitalize ps-3">Fees Table</h6>
							</div>
						</div>
					</div>
				</div>
				<div class="card-body px-0 pb-2">
					<div class="table-responsive p-0">
						<table class="table align-items-center mb-0">
							<thead>
								<tr>
									<th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
										Class
									</th>
									<th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">
										New pupils
									</th>
									<th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
										Returning pupils
									</th>
									<th class="text-secondary opacity-7"></th>
								</tr>
							</thead>
							<tbody>
								{% for class in classes %}
								<tr>
									<td class="align-middle text-center text-sm">
										<span>{{class.name|title}}</span>
									</td>
									<td class="align-middle text-center text-sm">
										<span>&#8358;{{class.new_fee|intcomma }}</span>
									</td>
									<td class="align-middle text-center text-sm">
										<span>&#8358;{{class.return_fee|intcomma }}</span>
									</td>
									<td class="align-middle">
										<a onclick="edit_fee({{ class.id }}, '{{class.name|title}}', {{ class.new_fee }}, {{ class.return_fee }})"
										type="button"
										class="text-secondary font-weight-bold text-xs"
										data-toggle="modal"
										data-target="#editFeesModal">Edit
										</a>
									</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="editFeesModal">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">
			<!-- Modal Header -->
			<div class="modal-header">
				<h4 class="modal-title">Edit <name></name> fees</h4>
			</div>
			<!-- Modal body -->
			<div class="modal-body">
				<div class="card-body">
					<form role="form"
						class="text-start"
						method="post">
						{% csrf_token %}
						<input type="hidden" name="id" id="id">
						<div class="input-group input-group-outline mb-3">
							<input type="number" class="form-control" name="new_fee" id="new_fee" placeholder="New fee" required/>
						</div>
						<div class="input-group input-group-outline mb-3">
							<input type="number" class="form-control" name="return_fee" id="return_fee" placeholder="Return fee" required/>
						</div>
						<div class="text-center">
							<button type="submit" class="btn bg-gradient-primary w-100 my-4 mb-2">
								Update
							</button>
						</div>
					</form>
				</div>
			</div>
			<!-- Modal footer -->
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">
					Close
				</button>
			</div>
		</div>
	</div>
</div>
<script>
	function edit_fee(id, name, _new, _return){
		$("name").html(name)
		$("#id").val(id)
		$("#new_fee").val(_new)
		$("#return_fee").val(_return)
	}
</script>
{% endblock %}